### ISSUE TITLE
Bot 

### ISSUE THREAD

**Issue by Dascx31** [DarkLord76865/Autofish-Fishing-Planet#9]
hello it has nothing to do with your project but I ask the question you never know do you have the project to make a bot for fisher online? because I would be really happy if this type of bot comes out good luck THANKS

**Comment by DarkLord76865** [comment]
Hi,
I don't have a bot for that game. I have never heard of that game before, but it seems cool. I don't have time to play it though, so it is very unlikely I will ever create a bot for that game. Sorry.

P.S. Creating a bot for that game would probably mean starting from scratch as the bot I created is very specific to Fishing Planet
